FROM mysql:8.0

# Set the MySQL root password, database name, and user credentials
ENV MYSQL_ROOT_PASSWORD=root_password
ENV MYSQL_DATABASE=my_app
ENV MYSQL_USER=user
ENV MYSQL_PASSWORD=password

EXPOSE 3306
